### ISSUE TITLE
Testing "extra_columns" branch

### ISSUE THREAD

**Issue by skanwal** [bjpop/varlap#4]
Hi Bernie,

As discussed, to add additional 'class' column for each variant, I have converted input vcf file to csv format.

Keeping you in loop as you had mentioned you haven't tested the recent changes in the newer branch, trying `extra_columns` branch code generated the expected output containing `class` column as specified in the input.

Thank you.
Sehrish.

**Comment by bjpop** [comment]
Thanks @skanwal. That is great, I'll close this issue now.
