### ISSUE TITLE
Could not install packages due to an EnvironmentError

### ISSUE THREAD

**Issue by skanwal** [bjpop/varlap#5]
Hi Bernie,

For record: when installing varlap on a cluster using pip and the instructions here https://github.com/bjpop/varlap#installing produced the following error:

```
Could not install packages due to an EnvironmentError: 
[('/g/data/gx8/projects/Kanwal_explore/git/varlap/.git/objects/84/a662f692f7722d5d7d1daa9e63
221fd00322fb', '/jobfs/2215744.gadi-pbs/pip-req-build-
exs05n64/.git/objects/84/a662f692f7722d5d7d1daa9e63221fd00322fb', "[Errno 13] Permission 
denied: '/jobfs/2215744.gadi-pbs/pip-req-build-
exs05n64/.git/objects/84/a662f692f7722d5d7d1daa9e63221fd00322fb'"), 
('/g/data/gx8/projects/Kanwal_explore/git/varlap/.git/objects/b5/09c26944918b075bc1ac9f8be4
b360e36633e9', '/jobfs/2215744.gadi-pbs/pip-req-build-
exs05n64/.git/objects/b5/09c26944918b075bc1ac9f8be4b360e36633e9', "[Errno 13] 
Permission denied: '/jobfs/2215744.gadi-pbs/pip-req-build-
exs05n64/.git/objects/b5/09c26944918b075bc1ac9f8be4b360e36633e9'"), 
('/g/data/gx8/projects/Kanwal_explore/git/varlap/.git/objects/57/d1fd244f5cb59a944835d4e76a1
f287a7ac512', '/jobfs/2215744.gadi-pbs/pip-req-build-
exs05n64/.git/objects/57/d1fd244f5cb59a944835d4e76a1f287a7ac512', "[Errno 13] Permission 
denied: '/jobfs/2215744.gadi-pbs/pip-req-build-
exs05n64/.git/objects/57/d1fd244f5cb59a944835d4e76a1f287a7ac512'"), 
('/g/data/gx8/projects/Kanwal_explore/git/varlap/.git/objects/28/9139bee141ebe40004e0b32fb9
d7bfc510d4d9', '/jobfs/2215744.gadi-pbs/pip-req-build-
exs05n64/.git/objects/28/9139bee141ebe40004e0b32fb9d7bfc510d4d9', "[Errno 13] 
Permission denied: '/jobfs/2215744.gadi-pbs/pip-req-build-
exs05n64/.git/objects/28/9139bee141ebe40004e0b32fb9d7bfc510d4d9'")]
```

**Solution:** I resolved it by assigning read and write permissions to `varlap/.git/objects` directory.
Mentioning it here in case someone else stumbles on the same issue.

Cheers,
Sehrish

**Comment by bjpop** [comment]
Thanks @skanwal. If possible can you please show the commands that lead to this error?

**Comment by skanwal** [comment]
Sure. The command that produces above error is:
`$ pip install -U /g/data/gx8/projects/Kanwal_explore/git/varlap`

**Comment by bjpop** [comment]
Thanks, and in what directory were you running the above command?

**Comment by skanwal** [comment]
From the git `varlap` directory - i.e. `/g/data/gx8/projects/Kanwal_explore/git/varlap` to be more precise.

**Comment by bjpop** [comment]
Thanks, and when you ran pip install, was the virtual environment activated?

**Comment by skanwal** [comment]
I tried it two ways:
1. From within a python3 conda environment
2. Outside any environment as suggested in installation point 3.

**Comment by bjpop** [comment]
With the help of @skanwal, having looked into this issue further, it seems likely that it is a problem with the directory permissions in the filepath where the varlap git repo was cloned.
We were able to solve the issue by cloning the repo into a different place, where the user definitely had read and execute permissions transitively on the repo.
I'll close this issue now, but please reopen if the problem pops up again.
